spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
#      更新或者创建数据表结构
      ddl-auto: update
#     显示sql语句
    show-sql: true



#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          #      更新或者创建数据表结构
#          auto: update
#    show-sql: true


